package server

const (
	UDP_NETWORK = "udp4"

	AN_SUC_COUNT_INIT  = 1
	AN_FAIL_COUNT_INIT = 0
	NS_COUNT_INIT      = 1
	AR_COUNT_INIT      = 0

	RR_NAME_INIT   = 0x00c
	RR_TTL_INIT    = 3600 * 24
	RR_RD_LEN_INIT = 4

	RR_AUTHOR_RD_LEN_INIT = 0
	RR_AUTHOR_TYPE_INIT   = 6
)
