package server

const (
	UDP_NETWORK = "udp4"
	DNS_PORT    = 53

	AN_SUC_COUNT_INIT  = 1
	AN_FAIL_COUNT_INIT = 1
	NS_COUNT_INIT      = 0
	AR_COUNT_INIT      = 0

	ANSWER_NAME_INIT   = 49164
	ANSWER_TTL_INIT    = 3600 * 24
	ANSWER_RD_LEN_INIT = 4
)
